version: '3.7'

services:
  app:
    build:
      context: .
    container_name: app
    image: 'spring-app:latest'
    depends_on:
      - postgres
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contentreviews
      - SPRING_DATASOURCE_USERNAME=contentreviews
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - minio_username=danilkha
      - minio_url=http://minio:9000
      - minio_password=donil0304
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: contentreviews
      POSTGRES_USER: contentreviews
      POSTGRES_PASSWORD: admin
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: danilkha
      MINIO_ROOT_PASSWORD: donil0304
    volumes:
      - minio-storage:/data
volumes:
  minio-storage:
  db-data: